### ISSUE TITLE
axis labels don't display properly

### ISSUE THREAD

**Issue by bananaturtlesandwich** [Gip-Gip/egui-plotter#5]
Hello! Thank you for the crate, it came around at a great time and is wonderful to work with
Unfortunately though I did find an issue with axis labels in that the y-axis label is not rotated and the x isn't there (?)
I'll try to have a look myself but I'll put this here if I don't know
![](https://github.com/Gip-Gip/egui-plotter/assets/71292624/2cc58925-6ac6-4852-bf6b-ac8f38223111)

**Comment by bananaturtlesandwich** [comment]
okay I looked at the draw_text implementation and it currently doesn't use rotation and anchor - just fixed anchor over here https://github.com/bananaturtlesandwich/egui-plotter but rotation still needs some time since instead have to use TextShape

**Comment by bananaturtlesandwich** [comment]
Ok looks like rotation plays weirdly with anchor so I'll look at that tomoz

**Comment by Gip-Gip** [comment]
Will look at it later today, sorry been busy with other life things. Thanks for contributing!

**Comment by bananaturtlesandwich** [comment]
I have a pr open that fixes it btw if you want to look at that

**Comment by Gip-Gip** [comment]
> I have a pr open that fixes it btw if you want to look at that

looking at it now, thanks again!
